framework:
    cache:
        pools:
            doctrine.result_cache:
                adapter: cache.adapter.filesystem
            doctrine.query_cache:
                adapter: cache.adapter.filesystem
            doctrine.metadata_cache:
                adapter: cache.adapter.filesystem
