security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    firewalls:
        main:
            pattern: ^/
            custom_authenticators:
                - App\Security\AppCustomAuthenticator
            form_login:
                login_path: app_login  # Route to the login page
                check_path: app_login  # Route to submit the login form
                default_target_path: app_home  # Target page after successful login
            logout:
                path: app_logout  # Path for logout
                target: app_home  # Redirect to the homepage after logout
            entry_point: App\Security\AppCustomAuthenticator  # Specify the entry point authenticator
            remember_me:
                secret: '%kernel.secret%'  # Custom secret for remember me
                lifetime: 31536000  # 1 year
                path: /  # Applies across the entire app

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
# Configuration for test environments (if needed)
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon

