name: app
type: "php:8.1"
disk: 2048

hooks:
    build: |
        set -e
        composer install
        npm install
        npm run build

relationships:
    database: "mysqldb:mysql"

web:
    commands:
        start: |
            php-fpm
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
