controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

test_email:
    path: /test-email
    controller: App\Controller\TestEmailController::sendTestEmail